services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "5173:5173"
volumes:
  sqlite_data:
  storage_data:
